# Locate CoreFoundation
# This module defines
# COREFOUNDATION_LIBRARY
# COREFOUNDATION_FOUND

IF(APPLE)
  SET(COREFOUNDATION_FOUND "YES")
  SET(COREFOUNDATION_LIBRARY "-framework CoreFoundation")
ELSE(APPLE)
  SET(COREFOUNDATION_FOUND "NO")
ENDIF(APPLE)
