# Locate CoreServices
# This module defines
# CORESERVICES_LIBRARY
# CORESERVICES_FOUND

IF(APPLE)
  SET(CORESERVICES_FOUND "YES")
  SET(CORESERVICES_LIBRARY "-framework CoreServices")
ELSE(APPLE)
  SET(CORESERVICES_FOUND "NO")
ENDIF(APPLE)
